version: '2'
services:
  db:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: esgi
      MYSQL_DATABASE: cleancode
      MYSQL_USER: dev
      MYSQL_PASSWORD: esgi
    ports:
      - 3306:3306
    volumes:
      - ../bdd:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links: 
          - db:db
      ports:
          - 8080:80
      environment:
          MYSQL_USER: dev
          MYSQL_PASSWORD: esgi
          MYSQL_ROOT_PASSWORD: esgi
volumes:
    persistent: